version: "2"

linters:
  enable:
  - errcheck
  - gosec
  - gocritic
  - misspell
  - revive
  - unused

formatters:
  enable:
  - gofmt
  - goimports

issues:
  uniq-by-line: false

run:
  issues-exit-code: 1
  timeout: 5m